/**
 * Classes para implementar a interface com usuário
 * Para maiores informações:
 * @link https://pt.wikipedia.org/wiki/MVC
 *
 */
package br.com.cidandrade.aulas.visao;

import br.com.cidandrade.aulas.controle.Controle;
import br.com.cidandrade.aulas.modelo.Pessoa;
import br.com.cidandrade.util.Entrada;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *
 * @author cidandrade
 * @version 1.0.22.10.18
 */
public class Visao extends javax.swing.JFrame
        implements PropertyChangeListener {

    Controle controle;

    /**
     * Creates new form Visao
     */
    public Visao() {
        initComponents();
        setLocationRelativeTo(null);
        controle = new Controle();
        controle.registrarObservador(this);
        atualizar(controle.getPessoa());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDados = new javax.swing.JPanel();
        jlNome = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jlProfissao = new javax.swing.JLabel();
        jtProfissao = new javax.swing.JTextField();
        jtReligiao = new javax.swing.JTextField();
        jlReligiao = new javax.swing.JLabel();
        jtbBarra = new javax.swing.JToolBar();
        jbNome = new javax.swing.JButton();
        jbProfissao = new javax.swing.JButton();
        jbReligiao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlNome.setText("Nome");

        jtNome.setEditable(false);

        jlProfissao.setText("Profissão");

        jtProfissao.setEditable(false);

        jtReligiao.setEditable(false);

        jlReligiao.setText("Religião");

        javax.swing.GroupLayout jpDadosLayout = new javax.swing.GroupLayout(jpDados);
        jpDados.setLayout(jpDadosLayout);
        jpDadosLayout.setHorizontalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlProfissao)
                    .addComponent(jtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlReligiao)
                    .addComponent(jtReligiao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jpDadosLayout.setVerticalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlProfissao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlReligiao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtReligiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jtbBarra.setRollover(true);

        jbNome.setText("Nome");
        jbNome.setFocusable(false);
        jbNome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbNome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNomeActionPerformed(evt);
            }
        });
        jtbBarra.add(jbNome);

        jbProfissao.setText("Profissão");
        jbProfissao.setFocusable(false);
        jbProfissao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbProfissao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbProfissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProfissaoActionPerformed(evt);
            }
        });
        jtbBarra.add(jbProfissao);

        jbReligiao.setText("Religião");
        jbReligiao.setFocusable(false);
        jbReligiao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbReligiao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbReligiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReligiaoActionPerformed(evt);
            }
        });
        jtbBarra.add(jbReligiao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jtbBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Responde ao botão "Nome" invocando a alteração
     */
    private void jbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNomeActionPerformed
        controle.alterarNome(Entrada.getString("Digite nome"));
    }//GEN-LAST:event_jbNomeActionPerformed

    /**
     * Responde ao botão "Profissão" invocando a alteração
     */
    private void jbProfissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProfissaoActionPerformed
        controle.alterarProfissao(Entrada.getString(
                "Digite profissão"));
    }//GEN-LAST:event_jbProfissaoActionPerformed

    /**
     * Responde ao botão "Religião" invocando a alteração
     */
    private void jbReligiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReligiaoActionPerformed
        controle.alterarReligiao(Entrada.getString(
                "Digite religião"));
    }//GEN-LAST:event_jbReligiaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbNome;
    private javax.swing.JButton jbProfissao;
    private javax.swing.JButton jbReligiao;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlProfissao;
    private javax.swing.JLabel jlReligiao;
    private javax.swing.JPanel jpDados;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtProfissao;
    private javax.swing.JTextField jtReligiao;
    private javax.swing.JToolBar jtbBarra;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent pce) {
        atualizar((Pessoa) pce.getNewValue());
    }

    private void atualizar(Pessoa p) {
        jtNome.setText(p.getNome());
        jtProfissao.setText(p.getProfissao());
        jtReligiao.setText(p.getReligiao());
    }
}
